version: '3.8'

services:
  my-pytorch-app-svd:
    image: pytorch_deposition:v1
    container_name: pytorch_container_svd
    shm_size: '15gb'
    volumes:
      - .:/workspace  # 将当前目录（包含所有文件）挂载到容器的/workspace
    ports:
      - "8889:8888"  # 如果需要可以映射端口，比如用于Jupyter Notebook
    command: ["tail", "-f", "/dev/null"]  # 持续运行，不退出
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

networks:
  default:
    driver: bridge